### ISSUE TITLE
브랜치 정리

### ISSUE THREAD

**Issue by dpdms529** [dpdms529/WDWM#47]
각자 크롤링 한 브랜치 기본 파일이랑 크롤링 최종파일만 있도록 정리해서 pull request해주세요
그리고 최종파일명을 브랜치 이름.py로 바꿔주세요
예를들어  lms브랜치면 최종 파일 이름을 lms.py로 해주세요
@dpdms529
@nature1216 
@soy-A 
@lalala5772

**Comment by nature1216** [comment]
기본 파일이면 README.md 인가용?

**Comment by dpdms529** [comment]
네 브랜치 첨에 만들었을때 있었던 파일들이요 근데 지워도 될거같긴한데 지워도되는게 맞는건지 확신이 안서서...일단은 지우지 말아봅시다

**Comment by nature1216** [comment]
넵
